Use message.cc and message.bcc instead of getattr(message, 'cc', []) and getattr(message, 'bcc', []) (#56)
* Use message.cc and message.bcc instead of getattr(message, 'cc', []) and getattr(message, 'bcc', [])

For some reason, getattr was causing this error for some email addresses:

  File "C:\Users\Aditya\test.py", line 68, in <module>
    proton.send_message(new_message, is_html=False)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aditya\protonmail-api-client\src\protonmail\client.py", line 321, in send_message
    'type': 1 if recipient_info['RecipientType'] == 1 else 32,
                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'RecipientType'

The to addresses are anyways using message.recipients, so it makes sense to use message.cc and message.bcc as well.

* Fix typo in readme